version: "3.8"

services:
  sendmessage:
    build: ./sendmessage
    image: "${DOCKERHUB_USERNAME}/sendmessage:latest"
    ports:
      - "3003:3003"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DYNAMODB_TABLE=${AWS_DYNAMODB_TABLE}

  getmessages:
    build: ./getmessages
    image: "${DOCKERHUB_USERNAME}/getmessages:latest"
    ports:
      - "3004:3004"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DYNAMODB_TABLE=${AWS_DYNAMODB_TABLE}

  deletemessage:
    build: ./deletemessage
    image: "${DOCKERHUB_USERNAME}/deletemessage:latest"
    ports:
      - "3005:3005"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DYNAMODB_TABLE=${AWS_DYNAMODB_TABLE}

  dynamodb_local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
