services:
  sendmessage:
    build: ./sendmessage
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - dynamodb

  getmessages:
    build: ./getmessages
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - dynamodb

  deletemessage:
    build: ./deletemessage
    ports:
      - "3003:3003"
    env_file:
      - .env
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb"

volumes:
  dynamodb_data:
