name: Deploy Chat Microservices to AWS EC2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_REPOSITORY: ztencontacto/chat-microservices
  APP_PORT: 5054

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          for service in sendmessage getmessages deletemessage; do
            echo "Building and pushing $service..."
            docker build -t ${{ env.DOCKER_REPOSITORY }}-$service:latest ./$service
            docker push ${{ env.DOCKER_REPOSITORY }}-$service:latest
          done

      - name: Deploy to EC2 Instances
        run: |
          echo "Starting deployment to EC2 instances..."
          IFS=',' read -ra HOSTS <<< "${{ secrets.EC2_HOSTS }}"
          for HOST in "${HOSTS[@]}"; do
            echo "Deploying to $HOST"
            ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}") ec2-user@$HOST << 'EOF'
set -x  # Modo debug para ver cada comando ejecutado

echo "Verificando si Docker está instalado..."
if ! command -v docker &> /dev/null; then
  echo 'Instalando Docker...'
  sudo yum update -y
  sudo yum install -y docker
  sudo systemctl start docker
  sudo systemctl enable docker
  sudo usermod -aG docker ec2-user
fi

echo "Verificando si Docker Compose está instalado..."
if ! command -v docker-compose &> /dev/null; then
  echo 'Instalando Docker Compose...'
  sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
fi

echo "Cargando imágenes Docker..."
for service in sendmessage getmessages deletemessage; do
  sudo docker pull ${{ env.DOCKER_REPOSITORY }}-$service:latest
done

echo "Reiniciando contenedores..."
sudo docker-compose down || true
sudo docker-compose up -d
EOF
            echo "Deployment to $HOST completed."
          done
