name: Deploy Chat Microservices to AWS EC2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_REPOSITORY: ztencontacto/chat-microservices
  APP_PORT: 5054

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          services=(sendmessage getmessages deletemessage)
          for service in "${services[@]}"; do
            echo "Building and pushing $service..."
            docker build -t ${{ env.DOCKER_REPOSITORY }}-$service:latest ./$service
            docker push ${{ env.DOCKER_REPOSITORY }}-$service:latest
          done

      - name: Deploy to EC2 Instances
        run: |
          echo "Starting deployment to EC2 instances..."
          IFS=',' read -ra HOSTS <<< "${{ secrets.EC2_HOSTS }}"
          for HOST in "${HOSTS[@]}"; do
            echo "Deploying to $HOST"
            ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}") ec2-user@$HOST "
              if ! command -v docker &> /dev/null; then
                echo 'Installing Docker...'
                sudo yum update -y
                sudo yum install -y docker
                sudo systemctl start docker
                sudo systemctl enable docker
              fi

              echo 'Installing Docker Compose...'
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-\$(uname -s)-\$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose

              echo 'Pulling latest Docker images...'
              services=(sendmessage getmessages deletemessage)
              for service in "${services[@]}"; do
                sudo docker pull ${{ env.DOCKER_REPOSITORY }}-$service:latest
              done

              echo 'Restarting containers...'
              sudo docker-compose down || true
              sudo docker-compose up -d
            "
            echo "Deployment to $HOST completed."
          done
